//
// Created by Daniel on 21.05.2023.
//

#ifndef BULLSANDCOWS_SRC_INTERFACES_IOBSERVABLE_H_
#define BULLSANDCOWS_SRC_INTERFACES_IOBSERVABLE_H_

class IObservable {


};
#endif //BULLSANDCOWS_SRC_INTERFACES_IOBSERVABLE_H_
