//
// Created by Daniel on 21.05.2023.
//

#ifndef BULLSANDCOWS_SRC_INTERFACES_IOBSERVER_H_
#define BULLSANDCOWS_SRC_INTERFACES_IOBSERVER_H_

class IObserver
{

};
#endif //BULLSANDCOWS_SRC_INTERFACES_IOBSERVER_H_
